/* 	The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */
// Completed on Wed, 16 Aug 2017
#include <iostream>
#include <fstream>
using namespace std;

int main() {

	int64_t T;
	int d;
	bool found = false;

	for (int i = 0;found == false; i++) {
		T = ((i + 1)*i) / 2;
		//cout << T << " ";
		d = 0;
		for (int64_t j = 1; j <= T; j++) {
			if (T%j == 0) {
				d++;
				//cout << j << " ";
			}	
			if (d > 5) {
				found = true;
				cout << T << endl;
				break;
			}
		}
		//cout << endl;
	}


	system("pause");
	return 0;
}