/*
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
*/
// Completed on Tue, 10 Oct 2017
#include <iostream>
using namespace std;

int main() {
	unsigned long long pn;	
	unsigned long long pnPlus;
	unsigned long long pnMinus1;
	long long pnMinus2;
	int N = 10000;
	unsigned long long*pns = new unsigned long long[N];

	for (unsigned int n = 1; n <= N; n++) {
		pn = n*(3 * n - 1) / 2;
		pns[n-1] = pn;
	}
	for (int i = 0; i < N; i++) {
		for (int j = 0; j < N; j++) {
			pnPlus = pns[i] + pns[j];
			for (int k = 0; k < N; k++) {
				if (pnPlus == pns[k]) {
					pnMinus1 = pns[j] - pns[i];
					pnMinus2 = pns[i] - pns[j];
					pnMinus2 = abs(pnMinus2);
					for (int l = 0; l < N; l++) {
						if (pnMinus1 == pns[l]) {
							cout << pns[l] << endl;
						}
					}
					for (int m = 0; m < N; m++) {
						if (pnMinus2 == pns[m]) {
							cout << pns[i] << " "<<pns[j]<<" "<<pnPlus<<" " <<pnMinus1<< " "<<pnMinus2<< endl;

						}
					}
				}
			}
		}
	}
	system("pause");
	return 0;
}