/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
// Completed on Wed, 11 Oct 2017
#include <iostream>
using namespace std;

int main() {
	unsigned long long tn;
	unsigned long long pn = 0;
	unsigned long long hn = 0;
	for (unsigned int t = 1; ;t++) {
		tn = t*(t + 1) / 2;
		for (unsigned int p = t/2; pn <= tn; p++) {
			pn = p*(3 * p - 1) / 2;
			if (pn == tn) {
				for (unsigned int h = p/2; hn <= pn; h++) {
					hn = h*(2 * h - 1);
					if (hn == pn) {
						cout << tn << endl;
					}
				}
			}
		}
	}
	system("pause");
	return 0;
}
