/*
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal,
is represented by a different number in the set.
*/
// Completed on Fri, 1 Dec 2017
#include <iostream>
#include <string>
using namespace std;

int main() {
	string triangle[100], square[100], pentagonal[100], hexagonal[100], heptagonal[100], octagonal[100];
	string p3str, p4str, p5str, p6str, p7str, p8str;
	int tr = 1, sq = 1, pe = 1, hex = 1, hep = 1, oc = 1;
	int p3, p4, p5, p6, p7, p8;
	int N = 10000;

	for (int i = 1; ; i++) {
		p3 = (i*(i + 1)) / 2; p3str = to_string(p3);
		p4 = pow(i, 2); p4str = to_string(p4);
		p5 = (i*(3 * i - 1)) / 2; p5str = to_string(p5);
		p6 = i*(2 * i - 1); p6str = to_string(p6);
		p7 = (i*(5 * i - 3)) / 2; p7str = to_string(p7);
		p8 = i*(3 * i - 2);	p8str = to_string(p8);

		if (p3 > 999 && p3 < N) { triangle[tr] = p3str; tr++; } //5
		if (p4 > 999 && p4 < N) { square[sq] = p4str; sq++; } //4
		if (p5 > 999 && p5 < N) { pentagonal[pe] = p5str; pe++; } //3
		if (p6 > 999 && p6 < N) { hexagonal[hex] = p6str; hex++; } //2
		if (p7 > 999 && p7 < N) { heptagonal[hep] = p7str;	hep++; } //1
		if (p8 > 999 && p8 < N) { octagonal[oc] = p8str; oc++; } //0
		if (p3 >= N && p4 >= N && p5 >= N && p6 >= N && p7 >= N && p8 >= N) break;
	}
	triangle[0] = to_string(tr - 1); square[0] = to_string(sq - 1); pentagonal[0] = to_string(pe - 1);
	hexagonal[0] = to_string(hex - 1); heptagonal[0] = to_string(hep - 1); octagonal[0] = to_string(oc - 1);

	string str = "012345";
	int size = str.length();
	int * control = new int[size]();
	bool post, breakme;

	string ** mem = new string*[size];

	mem[0] = octagonal;
	mem[1] = heptagonal;
	mem[2] = hexagonal;
	mem[3] = pentagonal;
	mem[4] = square;
	mem[5] = triangle;

	string ** permutation = new string*[size];
	int z = 1;

	string first_tmp1, first_tmp2, last_tmp1, last_tmp2, frs_tmp1, frs_tmp2, sec_tmp1, sec_tmp2;
	string mid1_tmp1, mid1_tmp2, mid2_tmp1, mid2_tmp2;

	string solutions[6];
	int countperm = 0;
	do {
		post = true; breakme = false;
		for (int i = 0; i < size; i++) {
			for (int j = 0; j < size; j++) {
				if (i != j && control[i] == control[j]) {
					post = false;
					break;
				}
			}
		}

		if (post) {
			countperm++;
			for (int i = 0; i < size; i++) {
				permutation[i] = mem[control[i]];
			}
			//first element in chain
			for (int i = 1; i <= stoi(permutation[0][0]); i++) {

				first_tmp1.resize(1, permutation[0][i][0]);
				first_tmp1.resize(2, permutation[0][i][1]);

				first_tmp2.resize(1, permutation[0][i][2]);
				first_tmp2.resize(2, permutation[0][i][3]);

				//last element in chain
				for (int j = 1; j <= stoi(permutation[5][0]); j++) {

					last_tmp1.resize(1, permutation[5][j][0]);
					last_tmp1.resize(2, permutation[5][j][1]);

					last_tmp2.resize(1, permutation[5][j][2]);
					last_tmp2.resize(2, permutation[5][j][3]);

					if (first_tmp1 == last_tmp2) {
						for (int k = 1; k <= stoi(permutation[1][0]); k++) {
							frs_tmp1.resize(1, permutation[1][k][0]);
							frs_tmp1.resize(2, permutation[1][k][1]);

							frs_tmp2.resize(1, permutation[1][k][2]);
							frs_tmp2.resize(2, permutation[1][k][3]);

							if (frs_tmp1 == first_tmp2) {
								for (int m = 1; m <= stoi(permutation[4][0]); m++) {
									sec_tmp1.resize(1, permutation[4][m][0]);
									sec_tmp1.resize(2, permutation[4][m][1]);

									sec_tmp2.resize(1, permutation[4][m][2]);
									sec_tmp2.resize(2, permutation[4][m][3]);

									if (sec_tmp2 == last_tmp1) {
										for (int n = 1; n <= stoi(permutation[2][0]); n++) {
											mid1_tmp1.resize(1, permutation[2][n][0]);
											mid1_tmp1.resize(2, permutation[2][n][1]);

											mid1_tmp2.resize(1, permutation[2][n][2]);
											mid1_tmp2.resize(2, permutation[2][n][3]);

											if (mid1_tmp1 == frs_tmp2) {
												for (int p = 1; p <= stoi(permutation[3][0]); p++) {
													mid2_tmp1.resize(1, permutation[3][p][0]);
													mid2_tmp1.resize(2, permutation[3][p][1]);

													mid2_tmp2.resize(1, permutation[3][p][2]);
													mid2_tmp2.resize(2, permutation[3][p][3]);

													if (mid2_tmp2 == sec_tmp1 && mid2_tmp1 == mid1_tmp2) {
														cout << permutation[0][i] << " " << permutation[1][k] << " " << permutation[2][n] << " " << permutation[3][p] << " " << permutation[4][m] << " " << permutation[5][j] << endl;
														cout << stoi(permutation[0][i]) + stoi(permutation[1][k]) + stoi(permutation[2][n]) + stoi(permutation[3][p]) + stoi(permutation[4][m]) + stoi(permutation[5][j]) << endl;
														cout << countperm << endl;
														system("pause");
													}
													mid2_tmp1 = "";
													mid2_tmp2 = "";

												}

											}
											mid1_tmp1 = "";
											mid1_tmp2 = "";
										}
									}
									sec_tmp1 = "";
									sec_tmp2 = "";
								}
							}
							frs_tmp1 = "";
							frs_tmp2 = "";
						}
					}
					last_tmp1 = "";
					last_tmp2 = "";
				}	
				first_tmp1 = "";
				first_tmp2 = "";
			}
		}

		control[size - 1]++;
		for (int i = size - 1; i >= 0; i--) {
			if (control[0] == size) {
				breakme = true;
				break;
			}
			if (control[i] == size) {
				control[i - 1]++;
				control[i] = 0;
			}
		}
		if (breakme) break;

	} while (true);

	system("pause");
	return 0;
}